//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "admin_menu")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub name: String,
    pub parent_id: i64,
    pub url: String,
    pub target: i16,
    pub menu_type: i16,
    pub is_hidden: bool,
    pub is_refresh: bool,
    pub permission: String,
    pub icon: String,
    pub display_order: i16,
    pub remark: String,
    pub created_by: i64,
    pub created_at: TimeDateTime,
    pub updated_by: i64,
    pub updated_at: TimeDateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
