//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub(crate) mod prelude;

pub(crate) mod admin_menu;
pub(crate) mod admin_role;
pub(crate) mod admin_role_menu;
pub(crate) mod admin_user;
pub(crate) mod admin_user_role;
