//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub(crate) use super::admin_menu::Entity as AdminMenu;
pub(crate) use super::admin_role::Entity as AdminRole;
pub(crate) use super::admin_role_menu::Entity as AdminRoleMenu;
pub(crate) use super::admin_user::Entity as AdminUser;
pub(crate) use super::admin_user_role::Entity as AdminUserRole;
